// Copies the design tokens and fonts into the browser extension (extension/), which can't use
// the app's Vite build. Run after changing design/tokens.css: npm run ext:assets
// src/lib/extensionRules.test.ts fails if extension/tokens.css falls out of date.

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const FONTS = [
  ["@fontsource-variable/geist/files/geist-latin-wght-normal.woff2", "geist.woff2"],
  ["@fontsource-variable/geist-mono/files/geist-mono-latin-wght-normal.woff2", "geist-mono.woff2"],
  ["@fontsource/instrument-serif/files/instrument-serif-latin-400-italic.woff2", "instrument-serif-italic.woff2"],
];

/** extension/tokens.css: design/tokens.css with local fonts instead of Google Fonts. */
export function extensionTokens(designCss) {
  const faces = `@font-face { font-family: "Geist"; src: url("fonts/geist.woff2") format("woff2"); font-weight: 100 900; }
@font-face { font-family: "Geist Mono"; src: url("fonts/geist-mono.woff2") format("woff2"); font-weight: 100 900; }
@font-face { font-family: "Instrument Serif"; src: url("fonts/instrument-serif-italic.woff2") format("woff2"); font-style: italic; }
`;
  const body = designCss.replace(/^@import url\([^)]*\);\s*/m, "");
  return `/* Generated by scripts/extension-assets.mjs from design/tokens.css. Don't edit. */\n${faces}\n${body}`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  mkdirSync(join(root, "extension/fonts"), { recursive: true });
  for (const [from, to] of FONTS) copyFileSync(join(root, "node_modules", from), join(root, "extension/fonts", to));
  writeFileSync(join(root, "extension/tokens.css"), extensionTokens(readFileSync(join(root, "design/tokens.css"), "utf8")));
  console.log("extension assets updated");
}
